[package]
name = "parse-display"
version = "0.1.0"
authors = ["frozenlib <frozenlib@users.noreply.github.com>"]
edition = "2018"

[dependencies]
parse-display-derive = { version = "0.1.0", path ="../parse-display-derive" }
lazy_static = "1.3"
regex = "1"