[package]
name = "parse-display"
version = "0.1.0"
authors = ["frozenlib <frozenlib@users.noreply.github.com>"]
edition = "2018"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
parse-display-derive = { version = "0.1.0", path ="../parse-display-derive" }