[package]
name = "parse-display-tests"
version = "0.1.1"
authors = ["frozenlib <frozenlib@users.noreply.github.com>"]
edition = "2018"

[dependencies]
parse-display = { version = "0.1.1", path = "../parse-display" }
